Iss hipcms 648
HiP-App/HiP-DataStore pull request #10
Opened 2017-05-18 13:59 UTC by Musaevt

2017-05-21 14:31 UTC, SvenEV requested changes

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore.Model/Rest/TagArgs.cs
> +        public string Tille { get; set; }
Typo (should be "Title")

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Controllers/TagsController.cs
> +        [ProducesResponseType(409)]
Method should return 409 if a tag with the given name already exists. This does not seem to be implemented yet.

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Controllers/TagsController.cs
> +            var tag = query.Where(x => x.Id == id).FirstOrDefault();
instead of ".Where(condition).FirstOrDefault()" you can use ".FirstOrDefault(condition)"

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore.Model/Rest/TagUpdateArgs.cs
> +    public class TagUpdateArgs
I discussed updates and PUT requests with Patrick (see latest comments on page "REST API for mobile content" on Confluence). We came to the conclusion that PUT requests shouldn't be used to update individual fields of an entity, but rather to replace an entity completely. Thus, PUT requests should not only specify values for fields that should be changed, but also for fields that do not change. In other words, POST and PUT always have exactly the same kinds of parameters, so TagUpdateArgs is redundant and we can just use TagArgs instead.

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Controllers/TagsController.cs
> +        public async Task<IActionResult> UpdateById(int id,[FromBody]TagUpdateArgs args)
UpdateById must not only add a reference to the image (if specified), but also remove any existing references (for example, if a PUT request changes the image ID from 2 to 5, remove the old reference to 2, then update the tag, then add a new reference to 5).

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Controllers/TagsController.cs
> +            if (!_referencesIndex.IsUsed(ResourceType.Tag, id))
Inverted if condition (remove the "!")

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Core/ReadModel/CacheDatabaseManager.cs
Case for TagDeleted is missing

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore/Core/WriteModel/MediaIndex.cs
> +        public bool IsImage(int id)
* Missing locks in IsImage and IsAudio
* `? true : false` is redundant

2017-05-21 14:31 UTC, SvenEV commented on HiP-DataStore.Model/Entity/Tag.cs
> +        public bool IsUsed { get; set; }
Property should be removed. Use `tag.Referencees.Count > 0` to check if a tag is in use.

2017-05-26 15:59 UTC, SvenEV requested changes

2017-05-26 15:59 UTC, SvenEV commented on HiP-DataStore/Core/WriteModel/TagIndex.cs
> +        private readonly Dictionary<int, TagInfo> _tag = new Dictionary<int, TagInfo>();
What do we need the event IDs for? I think a HashSet<string> should suffice, no need for a dictionary. Event IDs are unique anyway, so entries in the dictionary will never be updated or deleted.

2017-05-26 15:59 UTC, SvenEV commented on HiP-DataStore/Core/WriteModel/TagIndex.cs
> +                        _tag.Remove(ev.Id);
This won't work, see comment above. The TagCreated event and the TagDeleted event will have different event IDs, so this line never removes anything from the dictionary.

2017-05-26 19:54 UTC, Musaevt commented on HiP-DataStore/Core/WriteModel/TagIndex.cs
> +        private readonly Dictionary<int, TagInfo> _tag = new Dictionary<int, TagInfo>();
Itsn`t an event ID. It is a Tag ID which we have to create/update/delete

2017-05-26 23:06 UTC, SvenEV commented on HiP-DataStore/Core/WriteModel/TagIndex.cs
> +        private readonly Dictionary<int, TagInfo> _tag = new Dictionary<int, TagInfo>();
My fault. "ev.Id" is of course a tag ID, not an event ID, so everything is fine. Sorry!

2017-05-26 23:07 UTC, SvenEV approved these changes

2017-05-26 23:32 UTC, merged