Iss hipcms 637 (Routes APIs)
HiP-App/HiP-DataStore pull request #11
Opened 2017-05-21 13:52 UTC by SvenEV

This PR completes the Routes APIs (at least for now). Added APIs:
* GET /Routes/{id}
* PUT /Routes/{id}

I also fixed some architecture related issues.

2017-05-22 13:55 UTC, Musaevt requested changes

2017-05-22 13:55 UTC, Musaevt commented on HiP-DataStore/Controllers/RoutesController.cs
> +        [ProducesResponseType(404)]
Forgot statusCode 304

2017-05-22 13:55 UTC, Musaevt commented on HiP-DataStore/Controllers/RoutesController.cs
>          [ProducesResponseType(typeof(int), 200)]
Has to return 201 if success

2017-05-22 14:10 UTC, SvenEV commented on HiP-DataStore/Controllers/RoutesController.cs
>          [ProducesResponseType(typeof(int), 200)]
I agree, but then we should change this in all controllers

2017-05-26 19:09 UTC, Musaevt approved these changes

2017-05-26 19:09 UTC, merged