Iss hipcms 630 (Exhibits APIs)
HiP-App/HiP-DataStore pull request #12
Opened 2017-05-22 09:22 UTC by SvenEV

This PR completes the Exhibits APIs (for now). Added APIs:
* GET /Exhibits/{id}
* PUT /Exhibits/{id}

2017-05-22 14:53 UTC, Musaevt requested changes

2017-05-22 14:53 UTC, Musaevt commented on HiP-DataStore/Controllers/ExhibitsController.cs
>          [ProducesResponseType(typeof(int), 200)]
Status code has to be 201

2017-05-22 14:53 UTC, Musaevt commented on HiP-DataStore/Controllers/RoutesController.cs
> +                    response = StatusCode(422, ErrorMessages.ExhibitNotFoundOrNotPublished(invalidIds[0]));
Maybe add a list of all ids,which we have a problems with

2017-05-26 16:06 UTC, SvenEV commented on HiP-DataStore/Controllers/RoutesController.cs
> +                    response = StatusCode(422, ErrorMessages.ExhibitNotFoundOrNotPublished(invalidIds[0]));
This issue and other things related to validation will be addressed in a separate PR, if that's ok.

2017-05-26 19:10 UTC, Musaevt approved these changes

2017-05-27 08:59 UTC, merged